Malaysia Vaccination Metrics App Loom video Link- (https://www.loom.com/share/36adcbe8cc3842e19f7b7df9a5dcacb7?sid=5d8d9d34-189b-4acd-88c9-df9038497717)
Armynerh/malaysia_vaccination_metrics pull request #1
Opened 2023-09-14 16:06 UTC by Armynerh

Selected the API  to use .
Built file structure for React app.
Prepared routes and navigation in the app.
Made sure that a user can display a list of items and filter them. Data comes from the API.
Created the tests for the application.
Styled components to match the design provided.
Deployed the project and tested for final details.
Recorded a video for the project. https://www.loom.com/share/36adcbe8cc3842e19f7b7df9a5dcacb7?sid=5d8d9d34-189b-4acd-88c9-df9038497717
Created a good README and PR description.

2023-09-14 17:52 UTC, descholar-ceo requested changes
Hi @Armynerh 🤝 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- The project is deployed using Render properly, the home and detail page works as expected.
- The project styling is really commendable with great responsiveness
- The main purpose of the project has been achieved by having an index page, details page, and a filtering functionality 
- I like the most how you added the loading functionality, this improves the user experience

## Required Changes ♻️
_Check the comments under the review._

- [ ] Even though you highlight that the most interesting part of this project was choosing the API to use, the project’s specs require that you highlight a piece of code that interested you and you feel proud of the most, would you please re-record the video and showcase that part of the code you feel proud of?
- [ ] I would advise you to make a descriptive PR title, but shorter than what you have currently, you are showing the URL in the PR title but that makes it unreadable and hard to know what is the PR about
- [ ] The Acknowledgement in readme file should give appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/).
- [ ] Components: ErrorPage and Metrics should have test cases at least
- [ ] There is also a small issue with responsiveness in small screens (320px of width) on the details page, the cards are very small and letters are going off-card, you need to have a look into that as well
<img width="481" alt="Screenshot 2023-09-14 at 19 51 51" src="https://github.com/Armynerh/malaysia_vaccination_metrics/assets/56886064/64c6392f-cf49-4bd9-81fd-b6953c0fbca2">

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-14 17:52 UTC, descholar-ceo commented on src/component/Metrics.js
> +          <div key={metric.total} className="col-md-4 col-lg-3 p-5 m-3 shadow" style={i % 2 === 0 ? { backgroundColor: '#4268B0' } : { backgroundColor: '#4063A7;' }}>
- [ ] Would you remove a semicolon from this style? It's currently throwing an error on the console

2023-09-14 17:52 UTC, descholar-ceo commented on package.json
> +    "@testing-library/user-event": "^13.5.0",
- [ ] [Optional] You don't need to put these packages in project's dependencies, they for development environment, just put them in devDependencies

2023-09-15 00:24 UTC, binhussen requested changes
Hi @Armynerh , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- Sticked Given Design✔️
- Well Structured Code ✔️
- Used Git flow ✔️


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-15 00:24 UTC, binhussen commented on src/component/Metrics.js
> +          <div key={metric.total} className="col-md-4 col-lg-2  p-3 m-3 shadow" style={i % 2 === 0 ? { backgroundColor: '#4268B0' } : { backgroundColor: '#4063A7;' }}>
- Kindly, remove the semicolon from `backgroundColor: '#4063A7;'` to fix the console error as suggested by the previous reviewer
<img width="623" alt="2023-09-15_03-17" src="https://github.com/Armynerh/malaysia_vaccination_metrics/assets/52010789/2dcbe711-e704-462a-bde6-2c09f05b0e68">

2023-09-15 00:24 UTC, binhussen commented on README.md
> +I will like to thank Microverse for the learning Experience.
- Great Job for updating the video record, Even though you forgot to highlight a piece of code that interested you and you feel proud of the most, would you please re-record the video and showcase that part of the code you feel proud of as suggested by previous reviewer 👍

2023-09-15 00:46 UTC, Armynerh commented on README.md
> +I will like to thank Microverse for the learning Experience.
@binhussen  Thank you for your respponse, However, as the last reviewer suggested I remade the video and  clearly highlighte not 1 but multiple things I found interesting in the project.

2023-09-15 01:05 UTC, anagudelogu requested changes
# STATUS: CHANGES REQUIRED ♻️ 🚧 

Hi @Armynerh 👋🏼 
I'm Andres.

You've done a great job implementing some of the requested changes for this milestone 🚀, but there are still some which haven't been addressed yet. You're getting closer, keep up the good work! 🤖 🎆 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

 ## Highlights
✅ Great use of Git flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Descriptive PR title, summary and commit messages. 💬 


 ## Required Changes ♻️
_Check the comments under the review._

- [ ] Although you did a great presentation, what the previous reviews are asking about the video, and according to the requirements, you should highlight a piece of code that you're proud of. In the video, you spoke about features that made you proud, but you didn't show us 
the code behind the feature. Please consider adding this to your video! 🤓 🔧 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-15 01:42 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Kenny,  

**React Capstone project** is complete! 🏁 Great job, congratulations!  🎉💯🌟 

## Highlights 🎯 
🎲 Good job on introducing improvement to the presentation of the project!

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-15 07:45 UTC, ahmetbozaci commented
### Hello @Armynerh 
### _This is an additional review as a result of the second opinion request._ 

- Well done to implement the requirement.
_Even if some students were approved without following it, it's likely because the code reviewer missed it. The [requirement](https://github.com/microverseinc/curriculum-react-redux/blob/main/capstone/react_capstone.md#:~:text=you%20should%20also%20highlight%20some%20interesting%20piece%20of%20code%20or%20something%20you%20built%20that%20you%20are%20very%20proud%20of.) is straightforward: briefly showcase and explain a specific part of your project's code that you're proud of or that demonstrates your coding skills effectively._
___



### Cheers and Happy coding! 💻 👏
____
[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

2023-10-02 07:41 UTC, merged